### ISSUE TITLE
Passing through wall (Collision Bug). 

### ISSUE THREAD

**Issue by ash-jones** [ashpemb/TGPSEM2#25]
On level two if the player hits the wall to the left while falling down the gap on the right hand side the player will move through the wall and into the platform.

To reproduce this bug stand on the far right platform in level two, fall down the gap to the players left while moving into the side of the platform on the left this bug will happen 100% of the time.

Device: HTC Necus Tablet & PC.

![passing through wall collision bug](https://cloud.githubusercontent.com/assets/9088804/14295022/c5802dd4-fb6b-11e5-83e0-6458e1a6978c.gif)

**Comment by Malcom-Nubbins** [comment]
#41 
Issue fixed.
That and another wall were not being picked up by the SceneManager due to a mis-numbering of the wall sprites.
