### ISSUE TITLE
Level selection does not work

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#27]
**Reproduction:**
-Start a new game
-Select any World other then number one
-Click select level

**Consequences:**
-Game will start with World one, despite electing to start with World two or three.

**Occurrence:**
-100% time on the PC

**Comment by Malcom-Nubbins** [comment]
This is because we don't currently have any levels for the other worlds.

**Solution:**
Lock the other worlds if they dont have any levels, or populate those worlds with some new levels

**Comment by Flave229** [comment]
This issue is present because Alex has not yet implemented the new LevelSelect.

**Comment by Flave229** [comment]
I have added Alex to this issue.

Alex, would it be okay if you could prioritise the previously discussed level select? The one where all the worlds are in a circle?

**Comment by Flave229** [comment]
I believe this issue was intended to be closed a while ago.
