### ISSUE TITLE
Avatar gets stuck on level

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#28]
**Reproduction:**
-Access the second level
-Move along the positive X axis, over the first two buttons and past the first wall.
-Wait for 8~ seconds

**Consequences:**
-Player avatar gets stuck between two walls and is unable to escape or continue the game.

**Occurrence:**
-100% of the time on the PC.

![image](https://cloud.githubusercontent.com/assets/15687435/14315103/538d0fd4-fbf3-11e5-91e5-e2b440b8cd17.png)

**Comment by Flave229** [comment]
As mentioned in other bugs, a restart button should fix this.
