### ISSUE TITLE
Minor: Layer order is wrong at beginning of game.

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#29]
**Reproduction:**
-Start a new game

**Consequences:**
-"Start Game" button is being drawn behind a wall.

**Occurrence:**
-100% of the time on the PC.

![image](https://cloud.githubusercontent.com/assets/15687435/14315461/49cc8edc-fbf5-11e5-85f2-e98d46a46cb1.png)

**Comment by Flave229** [comment]
**Solution:**
Make the Start Button's Z-axis much higher. Or just remove it completely, as its use may be a little redundant.

**Comment by Malcom-Nubbins** [comment]
Shifted button up on the x-axis. Issue fixed.

**Comment by Flave229** [comment]
Nice, Thanks Josh.

**Comment by Malcom-Nubbins** [comment]
Seems this issue is still present. Reopening.
