### ISSUE TITLE
Collision detection issue

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#31]
**Reproduction:**
-Access level two
-Click on the far right button which moves the player avatar straight across the positive X axis, towards the right hand side of the screen.

**Consequences:**
-Player avatar "phases" through the wall and it has no collision detection when the level first begins.

**Occurrence:**
-100% of the time on the PC.

![image](https://cloud.githubusercontent.com/assets/15687435/14318155/7ad64f5a-fc03-11e5-964a-f865ef270acb.png)

**Comment by Malcom-Nubbins** [comment]
#40 
Fixed.
Issue was that the Solid Doors' collisions were only being checked when none of the 'hard-light' doors were open.
