### ISSUE TITLE
Minor: Need more instructions, possible draw bug

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#32]
Not really a bug, but on the "World" select screen I was unaware that each world had multiple levels associated with it.  I presumed that the cubes were representations of the levels, I did not realise that rotating the cubs caused different levels to be selected.

Also after rotating the "World: One" cube a few times, I had the following appear:

![image](https://cloud.githubusercontent.com/assets/15687435/14318533/2d618b70-fc05-11e5-8fb4-b1968e3603c9.png)

**Comment by Flave229** [comment]
The cube rotation is a confirmed bug, so this issue does count as a bug in my eyes.

Thanks for spotting this.

**Comment by Malcom-Nubbins** [comment]
Rotation of the World cube is a completely separate bug, and is not related to this issue report. Keeping the 'Bug' label, however, as the background sprites aren't behaving as they should be.

**Comment by Flave229** [comment]
Perhaps this issue should be labelled as a "Enhancement Suggestion" also, as the issue is suggesting we should make the level select clearer?

**Comment by Malcom-Nubbins** [comment]
#52 
Level select screen revamp has fixed this issue.
