### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by kieran154** [ashpemb/TGPSEM2#33]
Reproduction:
-Access level 2
-Click the start game button

Consequences:
-Game will crash and player will be unable to play

Occurrence:
-40%. Rare occurrence but a potential game breaker.

Device:
HTC Nexus Tablet & PC

![97831ab8f0b6df362d8f8331f7e699cc](https://cloud.githubusercontent.com/assets/15891283/14325801/e95e85c2-fc22-11e5-8522-568ffde5fe62.gif)

**Comment by Flave229** [comment]
Could you provide the line of code and file name it is breaking at?

Cheers.

**Comment by Malcom-Nubbins** [comment]
Did a bit of testing for this bug, happened once so far and crashed within the 'Switches' class, at Line 41 "this->scheduleUpdate();".
Happened after completing level 1 and moving to level 2.

**Comment by Flave229** [comment]
Interesting, thanks.

**Comment by kieran154** [comment]
I was trying to get the same one again, and managed to get a different one

![f48d40be914c63fe471f7ab517f626e4](https://cloud.githubusercontent.com/assets/15891283/14329265/93bbb8dc-fc32-11e5-87d3-33c0631bda13.png)

**Comment by Malcom-Nubbins** [comment]
I have possibly fixed this issue. I will keep it open, however, just in case crashes pop back up.

The problem was likely related to a change to the SceneManager I made, to try and fix the major bug with crates/players disappearing (on mobile/tablet). I have reverted the changes and the game seems more stable.

**Comment by Flave229** [comment]
This crash is not fixed. Needs further testing.

**Comment by Flave229** [comment]
Issue likely fixed in 147970042f66bc805c1ba670a7e6fa0501ba73b0, closing unless issue presents itself again.
