### ISSUE TITLE
Walking through solid barrier

### ISSUE THREAD

**Issue by kieran154** [ashpemb/TGPSEM2#35]
Reproduction
- Level 2
- Walk right along the bottom platform and player will walk through the solid metal barrier

Consequences
- Ability to walk through solid barrier
- Player gets stuck and cannot complete level

Device
- PC

![9fe32ff8aa309043a47e4aeb03047ce7](https://cloud.githubusercontent.com/assets/15891283/14326372/9a4c0952-fc25-11e5-8ead-cd67bc7aecad.gif)

**Comment by Malcom-Nubbins** [comment]
Issue fixed.
The collisions for the Solid doors was checking if the hard-light doors were open, allowing the player to pass through if one was open. Player should now be not able to pass through the solid doors at all.
