### ISSUE TITLE
player stuck behind barrier.

### ISSUE THREAD

**Issue by ash-jones** [ashpemb/TGPSEM2#38]
During level 2 the barrier on the left can respawn while the character is still behind it trapping the player and making the level unbeatable.

this bug occurs 100% of the time on PC and Android.

![bug4](https://cloud.githubusercontent.com/assets/9088804/14326605/a99e4e82-fc26-11e5-8ceb-d2e0f211288b.gif)

**Comment by Flave229** [comment]
**Solution:**
A retry button should be implemented to allow the player to restart the level. Having the player able to trap themselves is intentional, we do however, need to ensure the player can easily reset to avoid frustration.
