### ISSUE TITLE
Stuck in a wall

### ISSUE THREAD

**Issue by Mike430** [ashpemb/TGPSEM2#44]
**DESCRIPTION:**
When moving horizontally and colliding with a side section of floor, you can get stuck to the floor until you click somewhere opposite the face of the wall your stuck in.

**HOW TO REPLICATE:**
I've added a diagrammatic screen grab, basically, stand next to a drop, and click towards the other side of the drop. Your character will move towards the click, even while falling. If you hit the other side of the drop while falling you will snap back up to the centre of the floor.

**FREQUENCY:**
This happens every time I try it.

**SCREEN SHOTS:**
![bug 1](https://cloud.githubusercontent.com/assets/9351958/14334379/fd5da0de-fc4b-11e5-809e-75ab650cebb5.PNG)

**DEVICE:**
Windows 10 PC

**Comment by Malcom-Nubbins** [comment]
Possible cause is a collisions error. See comment on issue #26
