### ISSUE TITLE
Odd useless buttons on level select

### ISSUE THREAD

**Issue by Mike430** [ashpemb/TGPSEM2#45]
**Description:**
When I go onto the level select, A collection of un-clicable buttons usually appears at the same/similar randomised position. After going off the left side of the screen, they usually respawn on the other side of the screen but this time with random Y coordinates.

**Steps to reproduce:**
It usually happens by itself. If it doesn't, juggling the level cubes often provokes it. Just hang around on the menu and it will happen within the first 60 seconds.

**Occurrence:**
I've currently had it happen about 90% of the time.

**Screen shots**
![bug 5](https://cloud.githubusercontent.com/assets/9351958/14366911/0c91e062-fd0d-11e5-82ff-7c69f6039e83.PNG)
![bug 4](https://cloud.githubusercontent.com/assets/9351958/14366915/0e21260e-fd0d-11e5-9f78-339d7b4dfdfa.PNG)

**Device:**
Windows 10 PC

**Comment by Flave229** [comment]
Ah, this is left over debug code from when we were trying to implement scalable objects. @Rathie , could you remove these while working on the new Level Select?

Cheers.

**Comment by Mike430** [comment]
_CENSORED COMMENT_ - /I was expressing overt joy/

**Comment by Flave229** [comment]
Professionalism ^ :+1:

**Comment by Mike430** [comment]
You're right...

**Comment by Malcom-Nubbins** [comment]
#52 
Level select screen revamp has fixed this issue.
