### ISSUE TITLE
Levels can be completed instantly

### ISSUE THREAD

**Issue by BartoszGrabowski** [ashpemb/TGPSEM2#56]
**Desc:** When you start the level you can finish the level instantly by clicking the exit door before clicking start button.
**Steps to reproduce:** Start any level and press the exit door before clicking start
**occurance :** 100%
**Device:** PC windows 8.1
![husky](https://cloud.githubusercontent.com/assets/15784140/14587561/dbce83a2-04ac-11e6-8432-5afbe4e4e0b8.png)

**Comment by Flave229** [comment]
@Malcom-Nubbins can you take a look at this after assignment deadlines? It could be an incentive to finally remove the redundant start button.
