### ISSUE TITLE
Instantly complete all levels

### ISSUE THREAD

**Issue by LCranney** [ashpemb/TGPSEM2#58]
On every level, before the start button is pressed you can press the console next to the elevator and complete the level instantly. This means the level is completed with a time of 0:0.0

To Recreate this you need to select any level, do not press start, instead find the exit of the level and then press on the console next to the elevator.

This bug occurs 100% of the time on both PC and Android devices.

![husky1](https://cloud.githubusercontent.com/assets/15673916/14636810/898e426a-0625-11e6-9c0c-bc653f2ab18b.png)
![husky2](https://cloud.githubusercontent.com/assets/15673916/14636812/8be68db0-0625-11e6-93f9-855c89eae479.png)
![husky3](https://cloud.githubusercontent.com/assets/15673916/14636813/8e0af018-0625-11e6-8fe7-61efdaaca43a.png)
![husky4](https://cloud.githubusercontent.com/assets/15673916/14636815/8f77a518-0625-11e6-942e-01bf651eeb5a.png)

**Comment by Flave229** [comment]
See #56
