### ISSUE TITLE
Possible to get trapped with no indication

### ISSUE THREAD

**Issue by LCranney** [ashpemb/TGPSEM2#59]
It is possible to be trapped in several rooms on level 2 with no indication that this is going to happen and with no prompt to reset level if this occurs.

![huskytrapped1](https://cloud.githubusercontent.com/assets/15673916/14637131/462cf5f0-0627-11e6-835c-5c603a2a6193.png)
![huskytrapped2](https://cloud.githubusercontent.com/assets/15673916/14637135/47e1b444-0627-11e6-9a2c-a144783cc13c.png)

**Comment by Flave229** [comment]
See #60
