### ISSUE TITLE
Run animation plays on start button press on level 1

### ISSUE THREAD

**Issue by superduperbob** [ashpemb/TGPSEM2#62]
Description:
On loading level 1 and pressing start, the run animation begins. If the screen is pressed, the animation seems to stop.

Steps to reproduce:
Load level 1, press start. Shown in gif below.

Device:
LG G2 (Android 4.4)
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/15675303/14689499/7734f300-073f-11e6-91c5-deef701990a6.gif)

**Comment by Flave229** [comment]
I believe this was accidently fixed in the most recent commit 47a8340
