### ISSUE TITLE
Running animation continues when against wall

### ISSUE THREAD

**Issue by superduperbob** [ashpemb/TGPSEM2#64]
Description:
When the character is running and comes into contact with a wall, it will continue the run animation even though the character is not moving across the screen.

Device:
LG G2 (Android 4.4)

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/15675303/14690535/734215a2-0744-11e6-87a0-9ad2edd8607c.gif)

**Comment by Flave229** [comment]
See #55
