### ISSUE TITLE
Broken Running Animation

### ISSUE THREAD

**Issue by Hairbear01** [ashpemb/TGPSEM2#68]
Description
Upon starting level one, the character beings to animate like they are moving but no commands have been given to the character. It just animates on the spot at a very high rate.

Steps to Reproduce  
Start level one and do nothing.

Percentage of Occurrence    100%

Screenshot  Not applicable, video capture is needed for evidence.

Device Tested on  
Samsung Galaxy S5
Android Version 5.0

**Comment by Malcom-Nubbins** [comment]
This issue was fixed in 47a8340

Please update to the latest version.
