### ISSUE TITLE
Broken Animation On wall

### ISSUE THREAD

**Issue by Hairbear01** [ashpemb/TGPSEM2#70]
Description 
Telling the character to run into a wall on any level seems to cause the characters animation to continue running into the wall without actually moving. 

Steps to Reproduce  
Start any level and send the character into a wall.

Percentage of Occurrence    100%

Screenshot  Not applicable, video capture is needed for evidence.

Device Tested on  
Samsung Galaxy S5
Android Version 5.0

**Comment by Malcom-Nubbins** [comment]
This issue was fixed in 47a8340

Please update the game to the latest version.
