### ISSUE TITLE
Trapped on level two

### ISSUE THREAD

**Issue by w016869e** [ashpemb/TGPSEM2#72]
**Description:** On level two when the door closes on the top left section the player is trapped
Steps to reproduce: Enter top left room and wait for door to close.
**Device:** Windows 8.1 PC

![red1](https://cloud.githubusercontent.com/assets/15632252/14729576/02dece38-0837-11e6-9a96-5a9bf14bcce1.png)

**Comment by Flave229** [comment]
This is intentional. 

See #60, #59
