### ISSUE TITLE
Level 3: When block tapped, you cant do anything? Not sure what to do?

### ISSUE THREAD

**Issue by jonesy15** [ashpemb/TGPSEM2#76]
On level 3, when i tap either of the blocks that are dependant on the gravity, the player cant move until you tap it again? Not sure how to play this level so more instructions would be helpful, this happens 100% of the time, on pc - windows 10.

![screenshot 2016-04-22 04 28 21](https://cloud.githubusercontent.com/assets/15942050/14730967/ed8e4826-0843-11e6-9964-0c23bc55e245.png)

**Comment by Malcom-Nubbins** [comment]
Unless you have a touch screen PC, you cannot test that or the 4th level on PC. This is because it requires multi-touch for the box scaling.

**Comment by Flave229** [comment]
Tested on windows, therefore the level cannot be completed as @Malcom-Nubbins has identified. 

This issue is closed.
